### ISSUE TITLE
Use JetBrains Marketplace exception analyzer

### ISSUE THREAD

**Issue by duemir** [jenkinsci/idea-stapler-plugin#189] opened 2024-10-01 03:23 UTC
https://plugins.jetbrains.com/docs/marketplace/exception-analyzer.html documents how to send stack traces to the marketplace instead of a custom backend. If we do this, it makes #42 obsolete.

**Comment by SufyaanKhateeb** [comment] 2024-10-10 07:44
I can work on this. I have not previously worked with intellij plugins but as per the linked documentation, this task seems to be relatively simple. Anyways if this issue is assigned to me, I'll will create the PR and then we can look further, if it works fine or not and also if test this somehow.

**Comment by duemir** [comment] 2024-10-10 08:36
Sorry. It should indeed be a one line change, but I think it is blocked. This plugin currently targets 2022.3 but the extensions is available from 2023.3

**Closed** 2024-11-22 22:09 UTC
Labels: good first issue

**Comment by timja** [comment] 2024-11-28 22:11
I just submitted an exception although I don't see an exceptions tab: https://plugins.jetbrains.com/plugin/1885-jenkins-development-support/edit

**Comment by duemir** [comment] 2024-11-29 05:11
I would have thought, they enabled it on a per-Plugin level, not a per-user level. https://plugins.jetbrains.com/plugin/1885-jenkins-development-support/edit/exception-analyzer is the direct link. If it doesn't lead you anywhere, you might need to ask marketplace support to enable it for you as well. 

The exceptions tab is still empty, though 🤔

**Comment by duemir** [comment] 2024-11-29 05:20
I've asked about this in the same support case that got me access to Exceptions tab.

**Comment by timja** [comment] 2024-11-29 07:43
Link redirects me back to the overview page which is weird because I seem to have full access to the plugin

**Comment by duemir** [comment] 2024-11-29 21:10
Here is what I got from support:
> Access to the Exception Analyzer is granted per user account. Please provide me with the email addresses of your colleagues who need access, and I will add it to their accounts.
 
> There is indeed a processing delay between the time an exception is reported and is shown. However, it is also possible that there was an issue with sending of exception. Could you please try to reproduce and resend the exception if it is possible?

**Comment by timja** [comment] 2024-11-29 23:07
Can you add me please, timjacomb1@gmail.com

**Comment by timja** [comment] 2024-11-29 23:16
> Could you please try to reproduce and resend the exception if it is possible?

Unfortunately its not the easiest to reproduce on demand 😢

**Comment by duemir** [comment] 2024-12-03 05:57
@timja you should have access to the exception analyzer now, according to JetBrains support.

**Comment by timja** [comment] 2024-12-03 07:34
Yup I can see it weird that there’s nothing there though
